### ISSUE TITLE
After user select 'I want to stay' return to default

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#191]
When user choose 'I want to stay' in /delete flow' make sure it takes him back to default, like a 'cancel' operation

In the example below, I was in the middle of 'hashtag' process and then I started the delete flow. when I decided to stay and sent new item it looks like the bot expected to finish the hashtag flow.

![Screen Shot 2022-07-05 at 12 23 50](https://user-images.githubusercontent.com/25544824/177296614-371380bc-76b0-4f08-aa31-b9bd94af32ae.png)
.

**Comment by JerryVDP** [comment]
@assafza 
This is by design, it returns the user to his last state (which in this case is hashtag flow).
there's no such thing as "default" state (I know that in this case, you mean the state of adding items), and even if there was and the default state was the state of adding items, what if the user never finished the onboarding of the original responder? I cannot return him to that state in that case, and there could be even more limitations.

**Comment by assafza** [comment]
@JerryVDP  OK so in that case I think we should at least present some message: "Leave current flow?" (yes/No)
What do you think?

**Comment by assafza** [comment]
handled in persistent / dynamic flows #202
