### ISSUE TITLE
Exclamation mark in YES

### ISSUE THREAD

**Issue by WeKeren** [fredo-ai/Fredo-Public#320]
after "tell me more" I write yes, but I need a quotation mark for that 
If not it doesn't work

<img width="548" alt="Screen Shot 2022-10-26 at 10 26 16 AM" src="https://user-images.githubusercontent.com/113281951/197971402-801cd091-251a-4257-baf2-25223edc88e8.png">

**Comment by assafza** [comment]
@WeKeren FYI the problem here is that the template is not approved thus the buttons are not showing.

@JerryVDP this is the approved template:https://console.twilio.com/us1/develop/sms/senders/whatsapp-templates/HT8732de8f998c1c370f22d05151893a4a?frameUrl=%2Fconsole%2Fsms%2Fwhatsapp%2Ftemplates%2FHT8732de8f998c1c370f22d05151893a4a%3Fx-target-region%3Dus1
